# Generated by Django 5.2.1 on 2025-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sharshara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
                ("joylashuv", models.CharField(max_length=200)),
                ("tavsif", models.TextField()),
                ("rasm", models.ImageField(upload_to="sharsharalar/")),
                (
                    "xarita_iframe",
                    models.TextField(help_text="Google Maps iframe kodini joylang"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Waterfall",
        ),
    ]
